# app/config/security.yml
security:
    # Configurando las listas de control de acceso: mecanismo de seguridad más granular disponible en Symfony2.
    # Una ACL permite asignar permisos específicos a cada objeto y para cada usuario de la aplicación.
    acl:
        connection: default

    #firewall es el mecanismo con el que se protegen las diferentes partes de un sitio web
    firewalls:
        backend:
            pattern: ^/backend
            provider: superadmins
            http_basic: ~

        extranet:
            pattern: ^/admin
            provider: admins
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                # by default, the login form *must* be a POST, not a GET
                post_only: true
            remember_me:
                key: hpt1123
                lifetime: 604800 # 7 * 24 * 3600 = 604.800 = 1 semana
            logout:
                path: admin_logout

        frontend:
            pattern: ^/*
            provider: usuarios
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                # by default, the login form *must* be a POST, not a GET
                post_only: true
            remember_me:
                key: hpt1234
                lifetime: 604800 # 7 * 24 * 3600 = 604.800 = 1 semana
            logout:
                path: usuario_logout

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        #- { path: ^/servicios/*, roles: ROLE_USUARIO }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/backend/*, roles: ROLE_SUPERADMIN }

    providers:
        usuarios:
            entity: { class: HPT\UsuarioBundle\Entity\Usuario, property: email }
        admins:
            entity: { class: HPT\UsuarioBundle\Entity\Admin, property: username }
        superadmins:
            memory:
                users:
                    superadmin: {password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_SUPERADMIN }

    encoders:
        HPT\UsuarioBundle\Entity\Admin: { algorithm: sha512, iterations: 10 }
        HPT\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USUARIO]
        ROLE_SUPERADMIN: [ROLE_ADMIN]