<?php
/**
 * Created by PhpStorm.
 * User: Ramon
 * Date: 15/03/2015
 * Time: 17:52
 */

namespace HPT\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends EntityRepository
{
}