<?php

namespace HPT\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaRepository extends EntityRepository
{
    public function FindByNombre($nombre)
    {
        $em=$this->getEntityManager();
        $dql="SELECT s FROM HPTDefaultBundle:Sala s WHERE s.nombre=:nombre ORDER BY s.nombre ASC ";
        $query=$em->createQuery($dql);
        $query->setParameter('nombre',$nombre);
        $entity=$query->getResult();
        return $entity;
    }
}
