<?php

namespace HPT\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{
    public function FindAllCategorias()
    {
        $em=$this->getEntityManager();
        $dql="SELECT DISTINCT s.categoria FROM HPTDefaultBundle:Servicio s ORDER BY s.categoria ASC";
        $query=$em->createQuery($dql);

        $entity=$query->getResult();
        return $entity;
    }

    public function FindCategoria($cat)
    {
        $em=$this->getEntityManager();
        $dql="SELECT s FROM HPTDefaultBundle:Servicio s WHERE s.categoria = :categoria";
        $query=$em->createQuery($dql);
        $query->setParameter('categoria', $cat);

        $entity=$query->getResult();
        return $entity;
    }

    public function FindAllOrdered()
    {
        $em=$this->getEntityManager();
        $dql="SELECT s FROM HPTDefaultBundle:Servicio s ORDER BY s.categoria ASC";
        $query=$em->createQuery($dql);

        $entity=$query->getResult();
        return $entity;
    }
}
