<?php

namespace HPT\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrabajadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajadorRepository extends EntityRepository
{
}
